# Generated by Django 3.2.3 on 2021-09-02 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tgl_lahir',
            field=models.DateField(blank=True, default=datetime.datetime(1900, 1, 1, 0, 0), null=True),
        ),
    ]
