# Generated by Django 3.2.3 on 2021-09-01 14:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalHRD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DALAM PEMERIKSAAN', 'DALAM PEMERIKSAAN'), ('DISETUJUI', 'DISETUJUI'), ('DITOLAK', 'DITOLAK')], default='DALAM PEMERIKSAAN', max_length=20)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('hrd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.profile')),
            ],
        ),
        migrations.CreateModel(
            name='toQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_uuid', models.UUIDField(default=uuid.UUID('f790e7dc-8709-491f-afd8-9f4099efe0cf'), editable=False)),
                ('img_svg', models.ImageField(upload_to='qrcode/')),
                ('tk_klaim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klaim_registration.approvalhrd')),
            ],
        ),
        migrations.CreateModel(
            name='NoKPJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_kpj', models.CharField(max_length=15)),
                ('blth_keps', models.DateField()),
                ('blth_na', models.DateField(blank=True, null=True)),
                ('is_aktif', models.BooleanField(choices=[(False, 'Tidak Aktif'), (True, 'Aktif')], default=False)),
                ('user_kpj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.profile')),
            ],
            options={
                'verbose_name': 'KPJ',
                'verbose_name_plural': 'LIST KPJ',
            },
        ),
        migrations.CreateModel(
            name='DataTK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^\\d{16}$', 'Format NIK Tidak Sesuai')])),
                ('tempat_lahir', models.CharField(max_length=100)),
                ('tgl_lahir', models.DateField()),
                ('alamat', models.CharField(max_length=250)),
                ('nama_ibu', models.CharField(max_length=100)),
                ('no_hp', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator('^(08+[1-9])([0-9]{7,9})$', 'Format NO HP TIDAK SESUA!!!')])),
                ('propic', models.ImageField(blank=True, null=True, upload_to='profile/tk/')),
                ('status', models.CharField(choices=[('1', 'BELUM MENIKAH'), ('2', 'MENIKAH')], default='1', max_length=1)),
                ('nama_pasangan', models.CharField(blank=True, max_length=100, null=True)),
                ('tgl_lahir_pasangan', models.DateField(blank=True, null=True)),
                ('nama_anak_s', models.CharField(blank=True, max_length=100, null=True)),
                ('tgl_lahir_s', models.DateField(blank=True, null=True)),
                ('nama_anak_d', models.CharField(blank=True, max_length=100, null=True)),
                ('tgl_lahir_d', models.DateField(blank=True, null=True)),
                ('kpj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klaim_registration.nokpj')),
                ('npp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.perusahaan')),
            ],
            options={
                'verbose_name': 'DATA TK',
                'verbose_name_plural': 'LIST DATA TK',
            },
        ),
        migrations.CreateModel(
            name='DataKlaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('nama_rekening', models.CharField(max_length=100)),
                ('no_rekening', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^\\d{6,}$', 'No Rekening Harus Berupa Angka')])),
                ('file_kk', models.FileField(upload_to='kk/', validators=[django.core.validators.RegexValidator('.*\\.(jpg|JPG|JPEG|pdf|PDF)', 'Only Support PDF dan JPG')])),
                ('file_ktp', models.FileField(upload_to='ktp/', validators=[django.core.validators.RegexValidator('.*\\.(jpg|JPG|JPEG|pdf|PDF)', 'Only Support PDF dan JPG')])),
                ('file_paklaring', models.FileField(upload_to='vaklaring/', validators=[django.core.validators.RegexValidator('.*\\.(jpg|JPG|JPEG|pdf|PDF)', 'Only Support PDF dan JPG')])),
                ('file_lain', models.FileField(blank=True, null=True, upload_to='lain/', validators=[django.core.validators.RegexValidator('.*\\.(jpg|JPG|JPEG|pdf|PDF)', 'Only Support PDF dan JPG')])),
                ('created_on', models.DateField(auto_now_add=True)),
                ('data_tk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klaim_registration.datatk')),
            ],
            options={
                'verbose_name': 'DATA KLAIM',
                'verbose_name_plural': 'LIST DATA KLAIM',
            },
        ),
        migrations.AddField(
            model_name='approvalhrd',
            name='klaim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klaim_registration.dataklaim'),
        ),
    ]
