# Generated by Django 3.2.3 on 2021-09-14 07:11

from klaim_registration.models import TIPE_KLAIM
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('klaim_registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toqrcode',
            name='url_uuid',
            field=models.UUIDField(default=uuid.UUID(
                '65d09df9-755c-4a2b-928e-f9eb7c797529'), editable=False),
        ),
        migrations.AddField(
            model_name='dataklaim',
            name='sebab_klaim',
            field=models.CharField(max_length=5)
        ),
        migrations.AddField(
            model_name='dataKlaim',
            name='tipe_klaim',
            field=models.CharField(max_length=5, choices=TIPE_KLAIM)
        ),
    ]
