# Generated by Django 3.2.3 on 2021-09-02 14:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('klaim_registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datatk',
            name='no_hp',
        ),
        migrations.RemoveField(
            model_name='datatk',
            name='npp',
        ),
        migrations.RemoveField(
            model_name='datatk',
            name='propic',
        ),
        migrations.RemoveField(
            model_name='datatk',
            name='tempat_lahir',
        ),
        migrations.RemoveField(
            model_name='datatk',
            name='tgl_lahir',
        ),
        migrations.AlterField(
            model_name='toqrcode',
            name='url_uuid',
            field=models.UUIDField(default=uuid.UUID('d11cb735-4422-487a-9710-212bad9afff0'), editable=False),
        ),
    ]
