# Generated by Django 3.2.3 on 2021-09-03 03:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('klaim_registration', '0002_auto_20210902_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toqrcode',
            name='url_uuid',
            field=models.UUIDField(default=uuid.UUID('820fec93-5498-445a-b965-a2831bd55623'), editable=False),
        ),
    ]
