# Generated by Django 3.2.3 on 2021-09-14 07:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('klaim_registration', '0002_DataKlaim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataklaim',
            name='sebab_klaim',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='toqrcode',
            name='url_uuid',
            field=models.UUIDField(default=uuid.UUID('9269fc0f-9e37-4425-86c7-213b37900460'), editable=False),
        ),
    ]
