# Generated by Django 3.2.3 on 2021-09-14 08:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('klaim_registration', '0003_DataKlaim'),
    ]

    operations = [
        migrations.CreateModel(
            name='SebabKlaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=5)),
                ('keterangan', models.CharField(max_length=200)),
                ('keyword', models.CharField(max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='toqrcode',
            name='url_uuid',
            field=models.UUIDField(default=uuid.UUID('8227572e-0cb2-4bc5-a252-a10bea8a90b6'), editable=False),
        ),
        migrations.AlterField(
            model_name='dataklaim',
            name='sebab_klaim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klaim_registration.sebabklaim'),
        ),
    ]
