# Generated by Django 3.2.3 on 2021-09-14 04:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('klaim_registration', '0003_alter_toqrcode_url_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datatk',
            name='nik',
        ),
        migrations.AlterField(
            model_name='toqrcode',
            name='url_uuid',
            field=models.UUIDField(default=uuid.UUID('3f220897-948a-4fb4-b83b-4d62b895fef5'), editable=False),
        ),
    ]
